"""Competitor merchant patterns for M6 competitor analysis.

Frozen module-level constant -- 6 categories of financial competitors.
"""

from __future__ import annotations

COMPETITOR_MERCHANTS: dict[str, tuple[str, ...]] = {
    "big_nationals": (
        "JPMORGAN",
        "CHASE",
        "BANK OF AMERICA",
        "WELLS FARGO",
        "U.S. BANK",
        "US BANK",
        "PNC BANK",
        "PNC",
        "CITIBANK",
        "CITI CARD",
        "CAPITAL ONE",
    ),
    "regionals": (
        "BMO",
        "BMO HARRIS",
        "FIFTH THIRD",
        "5/3 BANK",
        "HUNTINGTON",
        "OLD NATIONAL",
        "FIRST MIDWEST",
        "WINTRUST",
        "TOWN BANK",
        "NORTH SHORE BANK",
        "LAKE FOREST BANK",
        "BYLINE BANK",
        "FIRST AMERICAN BANK",
        "ASSOCIATED BANK",
        "CIBC BANK",
        "MARQUETTE BANK",
        "REPUBLIC BANK",
        "FIRST MERCHANTS",
        "PEOPLES BANK",
        "PROVIDENCE BANK",
    ),
    "credit_unions": (
        "ALLIANT CREDIT UNION",
        "ALLIANT CU",
        "CONSUMERS CREDIT UNION",
        "BAXTER CREDIT UNION",
        "BCU",
        "CREDIT UNION 1",
        "CU1",
        "CORPORATE AMERICA FAMILY",
        "CAFCU",
        "FIRST NORTHERN CREDIT UNION",
        "ABRI CREDIT UNION",
        "NUMARK CREDIT UNION",
        "EARTHMOVER CREDIT UNION",
        "CHICAGO PATROLMEN",
        "NORTHSTAR CREDIT UNION",
        "UNITED CREDIT UNION",
        "SELFRELIANCE",
        "CHICAGO MUNICIPAL EMPLOYEES",
    ),
    "digital_banks": (
        "ALLY BANK",
        "DISCOVER BANK",
        "CAPITAL ONE 360",
        "SOFI BANK",
        "SOFI MONEY",
        "SOFI INVEST",
        "CHIME",
        "THE BANCORP",
        "STRIDE BANK",
        "VARO BANK",
        "VARO MONEY",
        "CURRENT CARD",
        "CURRENT MOBILE",
        "GO2BANK",
        "GREEN DOT",
        "REVOLUT",
        "MARCUS BY GS",
        "MARCUS SAVINGS",
        "GOLDMAN SACHS",
        "SCHWAB BANK",
        "CHARLES SCHWAB",
        "FIDELITY CASH",
        "ROBINHOOD",
        "BETTERMENT",
        "WEALTHFRONT",
    ),
    "wallets_p2p": (
        "PAYPAL",
        "VENMO",
        "CASH APP",
        "SQ*",
        "SUTTON",
        "LINCOLN SAVINGS",
        "APPLE CASH",
        "APPLE CARD",
        "GOOGLE PAY",
    ),
    "bnpl": (
        "KLARNA",
        "AFTERPAY",
        "AFFIRM",
        "ZIP PAY",
        "ZIP CO",
        "ZIP.CO",
        "QUADPAY",
        "SEZZLE",
    ),
}

ALL_COMPETITOR_PATTERNS: tuple[str, ...] = tuple(
    p for patterns in COMPETITOR_MERCHANTS.values() for p in patterns
)
